### ISSUE TITLE
Why does this library require session support?

### ISSUE THREAD

**Issue by cdimitroulas** [ewdave/passport-nylas#3]
Hi there,

Just trying to set up an OAuth2 flow for Nylas inside of FeathersJS and came across the error `OAuth authentication requires session support`.
Why does passport-nylas require session support?

**Comment by ewdave** [comment]
Hi @cdimitroulas when this library was created, I think I had this general idea/thought that almost everyone using passport (including its myriad plugins) defaults to using sessions in their API arch. This definitely shouldn't be enforced and can be handled differently instead of opting to fail when there seems to be no session in your request.

**Comment by cdimitroulas** [comment]
From what I have seen most OAuth2 flows do not require session support whereas OAuth1 do.

Either way, I got this working by adding a session - thanks for your response though :+1: 

This isn't really a great issue that I raised so feel free to close it unless you want to keep it open for tracking purposes and to add a different handling method for when there is no session

**Comment by ewdave** [comment]
Haha, Thanks, @cdimitroulas. I'm happy to know you got it to work. 👍  But you sure can design it to your taste though

> From what I have seen most OAuth2 flows do not require session support whereas OAuth1 do.

I meant I had this general idea/thought that almost everyone using passport(not OAuth2/OAuth2) (including its myriad plugins) defaults to using sessions
